const getInitialData = () => ([
  {
    id: 1,
    title: "Babel",
    body: "Babel merupakan tools open-source yang digunakan untuk mengubah sintaks ECMAScript 2015+ menjadi sintaks yang didukung oleh JavaScript engine versi lama. Babel sering dipakai ketika kita menggunakan sintaks terbaru termasuk sintaks JSX.",
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
  },
  {
    id: 2,
    title: "Functional Component",
    body: "Functional component merupakan React component yang dibuat menggunakan fungsi JavaScript. Agar fungsi JavaScript dapat disebut component ia harus mengembalikan React element dan dipanggil layaknya React component.",
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
  },
  {
    id: 3,
    title: "Modularization",
    body: "Dalam konteks pemrograman JavaScript, modularization merupakan teknik dalam memecah atau menggunakan kode dalam berkas JavaScript secara terpisah berdasarkan tanggung jawabnya masing-masing.",
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
  },
  {
    id: 4,
    title: "Lifecycle",
    body: "Dalam konteks React component, lifecycle merupakan kumpulan method yang menjadi siklus hidup mulai dari component dibuat (constructor), dicetak (render), pasca-cetak (componentDidMount), dan sebagainya. ",
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
  },
  {
    id: 5,
    title: "ESM",
    body: "ESM (ECMAScript Module) merupakan format modularisasi standar JavaScript.",
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
  },
  {
    id: 6,
    title: "Module Bundler",
    body: "Dalam konteks pemrograman JavaScript, module bundler merupakan tools yang digunakan untuk menggabungkan seluruh modul JavaScript yang digunakan oleh aplikasi menjadi satu berkas.",
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
  },
  {
    id: 7,
    title: "Webpack",
    body: "Webpack merupakan module bundler yang paling banyak digunakan saat ini. Webpack dapat menggabungkan seluruh modul JavaScript, CSS, gambar, dan berkas lainnya menjadi satu berkas.",
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
  },
  {
    id: 8,
    title: "React",
    body: "React merupakan library JavaScript yang digunakan untuk membangun antarmuka pengguna (user interface) berbasis web.",
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
  },
  {
    id: 9,
    title: "React Router",
    body: "React Router merupakan library yang digunakan untuk mengatur navigasi dalam aplikasi React.",
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
  },
  {
    id: 10,
    title: "React Testing Library",
    body: "React Testing Library merupakan library yang digunakan untuk melakukan pengujian pada aplikasi React.",
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
  },
  {
    id: 11,
    title: "Jest",
    body: "Jest merupakan library yang digunakan untuk melakukan pengujian pada aplikasi JavaScript.",
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
  },
  {
    id: 12,
    title: "React Testing",
    body: "React Testing merupakan pengujian yang dilakukan pada aplikasi React.",
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
  },
  {
    id: 13,
    title: "React DevTools",
    body: "React DevTools merupakan tools yang digunakan untuk melakukan debugging pada aplikasi React.",
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
  },
  {
    id: 14,
    title: "React Profiler",
    body: "React Profiler merupakan tools yang digunakan untuk melakukan profiling pada aplikasi React.",
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
  },
  {
    id: 15,
    title: "React.memo",
    body: "React.memo merupakan higher order component yang digunakan untuk mengoptimalkan performa aplikasi React.",
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
  },
  {
    id: 16,
    title: "React.lazy",
    body: "React.lazy merupakan fitur yang digunakan untuk melakukan lazy loading pada aplikasi React.",
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
  },
  {
    id: 17,
    title: "React.Suspense",
    body: "React.Suspense merupakan fitur yang digunakan untuk menampilkan loading state pada aplikasi React.",
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
  },
  {
    id: 18,
    title: "React.Fragment",
    body: "React.Fragment merupakan fitur yang digunakan untuk mengelompokkan beberapa elemen tanpa menambah elemen tambahan pada DOM.",
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
  },
  {
    id: 19,
    title: "React.StrictMode",
    body: "React.StrictMode merupakan fitur yang digunakan untuk menandai bagian-bagian dari aplikasi React yang perlu diperhatikan.",
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
  },
  {
    id: 20,
    title: "React.createContext",
    body: "React.createContext merupakan fitur yang digunakan untuk membuat context pada aplikasi React.",
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
  },
  {
    id: 21,
    title: "React.useContext",
    body: "React.useContext merupakan fitur yang digunakan untuk mengakses context pada aplikasi React.",
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
  },
  {
    id: 22,
    title: "React.createRef",
    body: "React.createRef merupakan fitur yang digunakan untuk membuat ref pada aplikasi React.",
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
  },
  {
    id: 23,
    title: "React.forwardRef",
    body: "React.forwardRef merupakan fitur yang digunakan untuk meneruskan ref pada aplikasi React.",
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
  },
  {
    id: 24,
    title: "React.useRef",
    body: "React.useRef merupakan fitur yang digunakan untuk mengakses ref pada aplikasi React.",
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
  },
  {
    id: 25,
    title: "React.useImperativeHandle",
    body: "React.useImperativeHandle merupakan fitur yang digunakan untuk mengubah instance ref pada aplikasi React.",
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
  },
]);

const showFormattedDate = (date) => {
  const options = {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric"
  }
  return new Date(date).toLocaleDateString("id-ID", options)
}

export { getInitialData, showFormattedDate };
